<?php
return ["Bank Indonesia ",
"Bank Negara Indonesia",
"Bank Rakyat Indonesia",
"Bank Tabungan Negara",
"Bank Mandiri",
"Bank Mutiara ",
"Bank Agroniaga",
"Bank Anda",
"Bank Artha Graha Internasional",
"Bank Bukopin",
"Bank Bumi Arta",
"Bank Capital Indonesia",
"Bank Central Asia",
"Bank CIMB Niaga ",
"Bank Danamon",
"Bank Ekonomi Raharja",
"Bank Ganesha",
"Bank Hana",
"Bank Himpunan Saudara 1906 ",
"Bank ICB Bumiputera",
"Bank ICBC Indonesia",
"Bank Index Selindo",
"Bank Internasional Indonesia Maybank",
"Bank Kesawan",
"Bank Maspion",
"Bank Mayapada",
"Bank Mega",
"Bank Mestika Dharma",
"Bank Metro Express",
"Bank Muamalat Indonesia",
"Bank Nusantara Parahyangan",
"Bank OCBC NISP ",
"Bank Permata",
"Bank SBI Indonesia",
"Bank Sinarmas",
"Bank Swadesi",
"Bank Syariah Mandiri",
"Bank Syariah Mega Indonesia",
"Bank Victoria Internasional",
"Bank Pan Indonesia Bank",
"Bank Anglomas Internasional Bank ",
"Bank Andara",
"Bank Artos Indonesia ",
"Bank Barclays Indonesia",
"Bank Bisnis Internasional ",
"Bank BRI Syariah",
"Bank Central Asia Syariah",
"Bank Dipo International",
"Bank Fama Internasional ",
"Bank Harda Internasional",
"Bank Ina Perdana",
"Bank Jasa Jakarta",
"Bank Kesejahteraan Ekonomi",
"Bank Liman International",
"Bank Mayora",
"Bank ANZ Panin Bank",
"Bank Agris",
"Bank Commonwealth",
"Bank BNP Paribas Indonesia",
"Bank DBS Indonesia",
"Bank KEB Indonesia",
"Bank Maybank Syariah Indonesia",
"Bank Mizuho Indonesia",
"Bank UOB Buana",
"Bank Rabobank Internasional Indonesia",
"Bank Resona Perdania",
"Bank Windu Kentjana Internasional",
"Bank Woori Indonesia",
"Bank Chinatrust Indonesia",
"Bank Sumitomo Mitsui Indonesia",
"Bank UFJ Indonesia",
"Bank Mitraniaga",
"Bank Multi Arta Sentosa",
"Bank Nationalnobu",
"Bank Pundi Indonesia",
"Bank Purba Danarta ",
"Bank Royal Indonesia",
"Bank Sinar Harapan Bali",
"Bank STMIK Binamulia ",
"Bank Syariah Bukopin",
"Bank Tabungan Pensiunan Nasional ",
"Bank Victoria Syariah",
"Bank Yudha Bhakti",
"Bank Centratama Nasional Bank ",
"Bank Pan Indonesia Bank Syariah",
"Bank Prima Master Bank",
"Bank Jambi ",
"Bank Kalsel ",
"Bank Kaltim ",
"Bank Sultra ",
"Bank BPD DIY ",
"Bank Nagari ",
"Bank DKI ",
"Bank Lampung ",
"Bank Kalteng ",
"Bank BPD Aceh ",
"Bank Sulsel ",
"Bank BJB ",
"Bank Kalbar ",
"Bank Maluku ",
"Bank Bengkulu ",
"Bank Jateng ",
"Bank Jatim ",
"Bank NTB ",
"Bank NTT ",
"Bank Sulteng ",
"Bank Sulut ",
"Bank BPD Bali ",
"Bank Papua ",
"Bank Riau Kepri ",
"Bank Sumsel Babel ",
"Bank Sumut ",
"Bank BNI Syariah",
"Bank BRI Syariah",
"Bank Maybank Syariah Indonesia",
"Bank Mega Syariah Indonesia",
"Bank Muamalat Indonesia",
"Bank Syariah Bukopin",
"Bank Syariah Mandiri",
"Bank Victoria Syariah",
"Bank Pan Indonesia Bank Syariah",
"Bank CIMB Niaga Syariah",
"Bank OCBC NISP Syariah",
"Bank Danamon Syariah",
"Bank Riau Kepri Syariah",
"Bank BCA Syariah",
"Bank BJB Syariah",
"Bank Permata Syariah"];
